print("Welcome to our school!!")
print("What is your name?")
myName = input()
print("What program or course are you enrolled in ?")
myProgram = input()
print("Where are you from?")
myPlace = input()
print("What made you choose this university?")
answer1 = input()
print("Have you explored the campus yet? Do you have a favorite spot so far?")
answer2 = input()
print("Are you staying on campus or off-campus? How’s your accommodation?")
answer3 = input()
print("What are you most excited about in university life?")
answer4 = input()
print("Have you joined any clubs or societies yet?")
answer5 = input()
print("Do you need any help navigating around campus or finding places?")
answer6 = input()
print("What are your hobbies or interests outside of academics?")
answer7 = input()
print("Is there anything about the university or the city you would like to know?")
answer8 = input()
print(f"Thank you for answering our questions {myName}!")
