# This programs says hello and ask for my name.

print("Hello world!!")
print("What is your name?")
myName = input()
print(f"It's good to meet you, {myName}.")
print(f"The length of your name is: {len(myName)}")
# print(len(myName))
print("What is your age?")
myAge = input()
print(f"You will be {int(myAge)+1} in a year")
print('Which primary school did you go?')
myPrimary=input()
print('That is a good school')
print('Which year did you sit for your K.C.P.E ?')
sitKcpe=input()
print(f"Thank you {myName} for answering our questions!")
